### Pandas

- 데이터 처리 및 분석을 위한 라이브러리
- 대용량 데이터를 안정적이면서도 간편하게 처리
- 서로 다른 데이터타입으로 열을 구성할 수 있음 <br>
(참고) Numpy : 전체 배열 원소를 동일한 타입으로 제한
- 주요 기능
    - 데이터 입출력 : csv, excel, RDB, JSON 등 다양한 포맷의 데이터를 효율적으로 처리할 수 있는 형식을 사용
    - 데이터 가공 : 분리, 결합, 계층, 피봇 등
    - 통계 분석 처리

#### 자료형
- Series <br>

    - 1차원 배열과 유사한 자료형
    - 색인(index) : 행 번호
        - 각각의 데이터에 부여하는 속성으로 기본값은 0부터 1씩 증가하는 숫자 지정
        - index 파라미터를 통해 새로운 값으로 변경 가능
        - 리스트, 튜플 타입으로 새로운 값을 전달해야하며 다차원 자료형은 사용할 수 없음
        - 전달하는 색인의 개수와 데이터의 개수가 일치해야 함
    - 각각의 색인과 데이터가 매핑되어 있으므로 dictionary 자료형과 유사
    - 여러 가지 데이터 타입 사용 가능

<img src="img/series_example.png" width="250" align="center">

In [93]:
# pandas 라이브러리 및 Series, DataFrame 네임스페이스 불러오기
import pandas as pd

In [94]:
# Series 생성
pd.Series()

C:\Users\user\AppData\Local\Temp\ipykernel_19808\1418016953.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  pd.Series()


Series([], dtype: float64)

### Series 생성

- 하나의 값(숫자, 문자) 또는 자료형(리스트, 튜플, np 배열)으로 데이터 전달

### Series 속성

- 속성은 소괄호를 붙이지 않음
- index : series 객체의 인덱스 배열을 반환
- values : series 객체의 데이터(값) 배열을 반환
- name : series 객체의 이름을 반환 
- dtype : series 객체의 데이터 타입을 반환
- size : series 객체의 데이터 개수(길이)를 반환
- shape : series 객체의 구조(행, 열, 차원)를 반환

In [54]:
# 숫자 10을 데이터로 가지고 있는 Series
# 결과 해석
# 왼쪽 0 : 자동으로 생성되는 기본 인덱스번호(0번부터 시작)
# 오른쪽 10 : 입력한 데이터 값
s1 = pd.Series(10)
s1

0    10
dtype: int64

In [55]:
# 데이터 내부에 저장된 값 확인
s1.values

array([10], dtype=int64)

In [56]:
# 인덱스 번호 확인
# RangeIndex : 기본적으로 부여되는 인덱스번호가 사용되고 있을때 지정되는 자료형
s1.index

RangeIndex(start=0, stop=1, step=1)

In [57]:
# 문자
s2 = pd.Series('abc')
s2

0    abc
dtype: object

In [58]:
# 인덱스 확인
s2.index

RangeIndex(start=0, stop=1, step=1)

In [59]:
# 리스트 자료형
s3 = pd.Series([10, 20, 30])
s3

0    10
1    20
2    30
dtype: int64

In [60]:
# 데이터타입이 서로 다른 리스트 자료형
s4 = pd.Series([10.3, 'test', 200, [1, 2, 3]])
s4

0         10.3
1         test
2          200
3    [1, 2, 3]
dtype: object

In [61]:
# 데이터 확인
s4.values

array([10.3, 'test', 200, list([1, 2, 3])], dtype=object)

In [62]:
# 인덱스 확인
s4.index

RangeIndex(start=0, stop=4, step=1)

In [63]:
# 튜플도 리스트처럼 1차원 자료로 주면 각각 내부자료를 풀어서 집어넣습니다.
s5 = pd.Series((1, 2, 3, 4, 5.0))
s5

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [64]:
# 데이터 확인
s5.values

array([1., 2., 3., 4., 5.])

In [65]:
# 인덱스 확인
s5.index

RangeIndex(start=0, stop=5, step=1)

In [66]:
# 딕셔너리 자료형(자동으로 라벨 부여, key가 index, value가 실제 데이터)
s6 = pd.Series({'a':10, 'b':20, 'c':30})
s6

a    10
b    20
c    30
dtype: int64

In [67]:
# 인덱스 새롭게 지정하기
# 인덱스 속성(길이)를 참조하여 리스트, 튜플 타입으로 전달
# 라벨 인덱스가 없던 경우 => 새롭게 라벨 인덱스 부여
# 라벨 인덱스가 있던 경우 => 기존에 있던 라벨 인덱스에 덮어씌우기
s5.index

RangeIndex(start=0, stop=5, step=1)

In [68]:
# 인덱스를 새롭게 지정할때는 RangeIndex이 범위만큼 길이를 가지는 리스트를 대입해줍니다.
# 행 개수(데이터 개수)와 동일한 길이의 리스트를 전달해야 합니다.
s5.index = [2020, 2021, 2022, 2023, 2024]

In [69]:
s5

2020    1.0
2021    2.0
2022    3.0
2023    4.0
2024    5.0
dtype: float64

In [70]:
# 인덱스를 지정하여 객체 생성
# 인덱스 객체에 대해서 아이템 참조는 가능
s5.index

Int64Index([2020, 2021, 2022, 2023, 2024], dtype='int64')

In [74]:
# 인덱스 객체 내부의 단일 라벨 인덱스만 하나 딱 잘라서 변경하는것은 불가능
s5.index[-1] = 2025

TypeError: Index does not support mutable operations

In [75]:
# 인덱스 라벨링 수정시 바꿀 부분만 변경한 전체 인덱스 자료를 대입해야합니다.
s5.index=[2020, 2021, 2022, 2023, 2025]
s5

2020    1.0
2021    2.0
2022    3.0
2023    4.0
2025    5.0
dtype: float64

In [76]:
# Series 함수의 index 파라미터를 이용해 생성과 동시에 인덱스 라벨 부여 가능
# pd.Series(data, index=[......])
s7 = pd.Series([10, 20, 30, 40], index=['mon', 'tue', 'wed', 'thu'])
s7

mon    10
tue    20
wed    30
thu    40
dtype: int64

In [77]:
# 데이터 확인
s7.values

array([10, 20, 30, 40], dtype=int64)

In [78]:
# 인덱스 확인
s7.index

Index(['mon', 'tue', 'wed', 'thu'], dtype='object')

### dictionary 자료형과 유사한 Series 자료형

In [79]:
# dictionary 자료형으로 Series 생성
data = {'서울':100, '경기':200, '강원':300, '부산':400}
sample = pd.Series(data)
print(data)
print(sample)

{'서울': 100, '경기': 200, '강원': 300, '부산': 400}
서울    100
경기    200
강원    300
부산    400
dtype: int64


In [80]:
# Series 객체와 in 연산자
# dicionary와 유사 : in 연산자를 사용ㅎ 내부 요소 검사시
# key값에 해당하는 라벨을 이용해 해당 요소가 있는지 없는지 여부를 True, False로 출력
print(100 in data)
print(100 in sample)

False
False


In [81]:
# for문에서 in 연산자로 접근 : Series의 value값을 참조
for key in data:
    print(key)
print("-----------------------")
for index in sample.values:
    print(index)

서울
경기
강원
부산
-----------------------
100
200
300
400


In [82]:
# sample의 인덱스 : 서울, 경기, 강원, 부산 =>  서울, 경기, 강원, 제주로 변경해주세요.
# 지정한 index 기준으로 Series 생성
# 사용하는 인덱스에 없는 값은 Series에 NaN으로 저장
# NaN : Not a Number(결측치) -> numpy에서 해당 위치에 값이 없을을 나타낼떄 사용하는 자료
# None :파이썬 기본자료형에서 null처럼 쓰이는 자료
sample.index = ['서울', '경기', '강원', '제주']
sample

서울    100
경기    200
강원    300
제주    400
dtype: int64

### Series s6의 첫 번째 데이터 -> 인덱스 0으로 조회
### Series객체[인덱스번호 or 라벨숫자]


In [83]:
print(s6.index[0])
print(s6[0])

a
10


In [84]:
# Series s6의 인덱스 a에 매칭된 데이터 조회
s6['a']

10

In [85]:
# Series s7의 인덱스 tue에 해당하는 데이터 값을 변경
# 인덱스(라벨링)은 개별적으로 하나하나 변경 불가능
# 인덱스에 매칭된 데이터는 개별 데이터별 변경 가능
s7['tue'] = 700
s7

mon     10
tue    700
wed     30
thu     40
dtype: int64

In [86]:
# 시리즈에서 원하는 로우(행)만 조회하기 : 조회할 로우명을 리스트로 묶어서 전달
# Series s7에서 wed, mon 라벨 조회
# 이중 리스트를 사용해서 조회해야 합니다. -> s7['wed', 'mon']으로 조회 시 에러 발생

s7[['wed', 'mon']]

wed    30
mon    10
dtype: int64

### 슬라이싱

- Series객체[시작인덱스 : 끝 인덱스 : 간격]
- 특정 범위의 값을 선택하거나 변경
- 기본 숫자 인덱스 또는 새로운 인덱스 모두 사용 가능
- 기본 숫자 인덱스를 사용해서 슬라이싱 할 때는 끝 인덱스 미포함
- 라벨 인덱스를 사용해서 슬라이싱 할 때 끝 인덱스까지 모두 포함


In [100]:
# 인덱스 0~2(포함)까지 조회
s1 = pd.Series([10, 20, 30, 40, 50]).index=list('abcde')
s1

['a', 'b', 'c', 'd', 'e']

In [102]:
#RandeIndex = 0, 1
s1[0 : 2]

['a', 'b']

In [103]:
# 라벨 'a'
s1['a' : 'c']

TypeError: slice indices must be integers or None or have an __index__ method

In [104]:
# 0 ~ 3 범위를 2개 간격으로 인덱싱
s1[0:4:2]

['a', 'c']

In [91]:
s1['b' : 'd' : 2]

TypeError: cannot do slice indexing on RangeIndex with these indexers [b] of type str

### 조건색인(Boolean Indexing)
- 객체에 벡터와 스칼라 연산을 적용하여 True인 데이터만 반환

<img src="img/conditional_index.png" width="700" align="center">

In [105]:
s2 = pd.Series([10, -3, 14, 70, -44, -18, -5, 1, -2, 12, 5]).index=('abcdefghijk')
s2

TypeError: Index(...) must be called with a collection of some kind, 'abcdefghijk' was passed

In [107]:
s2<0

TypeError: '<' not supported between instances of 'str' and 'int'