# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

In [1]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 조건색인(Boolean Indexing)
- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환


In [3]:
# 2차원 배열 생성
# 6 *4 로 0 ~23을 만들어봐요
b =  np.arange(0, 24).reshape(6, 4)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (6, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [4]:
# 스칼라 연산을 이용해서 10보다 큰 요소 조회하기
b > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
# 조건색인 방법
# 자료 (자료를 포함한 조건식)
b[b>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [12]:
# 조건색인을 이용해 b에서 짝수인 자료만 남겨보세요
# 조건색인에 2개 이상의 조건을 걸고 싶을 때는 각 조건을 하나마다()로 감쌉니다.
# 조건 사이를 and인 경오 &로 or인 경우에는 |로 연결해줍니다.

b[ (b%2 == 0) & (b != 0)]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

### 연습문제

다음 점수의 합격자 평균을 구해주세요

합격은 60점 이상입니다.

[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51]

In [13]:
a = np.array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34, 55, 56, 51])

In [14]:
a

array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51])

In [15]:
a[a>=60]

array([83, 75, 86, 60, 94, 80, 73, 80, 65])

In [16]:
np.mean(a[a>=60])

77.33333333333333

In [18]:
# 0부터 3까지 범위로 1씩 증가하는 2*2 구조 배열 생성
arr1 = np.arange(0, 4).reshape(2, 2)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (2, 2)  
    dimension : 2  
    dtype : int32
    data :
 [[0 1]
 [2 3]]
    


In [19]:
# 깊은복사 2 : .copy()를 이용하면 깊은 복사가 일어납니다.
arr2 = arr1.copy()
arr2

array([[0, 1],
       [2, 3]])

In [20]:
# 얕은복사 : array 도 참조형 변수여서 그냥 대입하면 얕은 복사입니다.
arr3 = arr1
arr3

array([[0, 1],
       [2, 3]])

### 배열 변환

#### 1. 전치(Transpose)
- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음

In [21]:
# 1이상 12
arr1 = np.arange(0, 5).reshape(2, 2)

ValueError: cannot reshape array of size 5 into shape (2,2)